### PR TITLE
Allow iframes

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/bookmarks/issues/180

### CODE REVIEW

**Comment by blizzz** [comment]
@shtrom Mind testing?

**Comment by shtrom** [comment]
I'll try to do this over the weekend.

**Comment by blizzz** [comment]
Thank you!

**Comment by entyrion** [comment]
Hi all, not sure if this helps, but this does seem to work for me per my comment in #180. Thanks so much!

**Comment by blizzz** [comment]
@entyrion absolutely, thank you!

I wait for @shtrom feedback over the WE and - if positive - merge it subsequently.

**Comment by shtrom** [comment]
Yup, this seems to fix the issue! Cheers!

**Comment by ezraholm50** [comment]
entyrion you're the best thanks alot!

**Comment by blizzz** [comment]
Thanks guys for testing!

**Comment by starkruzr** [comment]
Can someone explain this fix? Sorry, I'm not a dev but am on OC 8.1 and the "Import" button doesn't actually do anything when I click it. Formerly, it would at least open a dialog to import my bookmarks XML, but when it was finished I wouldn't have anything in there. Help?

**Comment by ezraholm50** [comment]
quote from entyrion

Hi all,

From my testing, I can confirm that #182 does in fact work for me. To @ezraholm50 and others, I basically:

    navigated to my ownCloud installation's app folder, and then to the 'controller' folder within the boomkarks directory: [YMMV depending on your installation]/owncloud/apps/bookmarks/controller

    opened [YMMV depending on your installation]/owncloud/apps/bookmarks/controller/webviewcontroller.php with a text editor.

    added the green lines and subtracted the red line in the code from https://github.com/owncloud/bookmarks/pull/182

    saved changes, restarted oC server, used the bookmarks app's import tool from the web UI.

    import successful; seems to stick after subsequent server reboot!

Hope this helps!

**Pull request merged**
