### PR TITLE
Prevent dialog stating "Bookmark added. You can close the window now.…

### PR DESCRIPTION
**Pull request by tmciver**
…" from

displaying when creating a bookmark using bookmarklet. Addresses issue 136.

### CODE REVIEW

**Comment by blizzz** [comment]
@tmciver very good, thank you! One little improvement: we can actually show a success message or green checkmark, so there user really nows it's done. For a second or two (as [recommended here](https://github.com/owncloud/bookmarks/issues/136#issuecomment-119716068)), and then close it automatically.

**Comment by tmciver** [comment]
Sorry for the delay.  Sure, I should be able to add that.  Is there already a way to do this in OC?  I took a quick look at https://github.com/owncloud/core/blob/master/core/js/oc-dialogs.js but it wasn't obvious to me if that sort of dialog was there.

**Comment by blizzz** [comment]
For the record: suggested native  and underscorejs's delay methods on IRC.

**Comment by blizzz** [comment]
> PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "bookmarks.web_view.index" as such route does not exist.' in /home/travis/build/owncloud/core/3rdparty/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php:134

Is what Travis reports. The log is not kept long, though. It does not survive any 5 minutes… @DeepDiver1975 possible to keep it a little bit longer?

Anyway, when I run tests locally, they succeed.

**Comment by blizzz** [comment]
*rebased*

**Comment by blizzz** [comment]
Tests succeed :) @tmciver thank you very much :)

**Pull request merged**
