### PR TITLE
fix add button to show in same line as input field

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @ganomi @TtuxX @wakeup @owncloud/designers

### CODE REVIEW

**Comment by ganomi** [comment]
some changes to make it look neat and tidy

**Comment by TtuxX** [comment]
@jancborchardt Great :+1:

**Comment by jancborchardt** [comment]
@ganomi it was intentional to overlap the field and button to make clear they belong together – can you remove that commit? Also, when the button text is not shown, the loading spinner should show directly in the button.

**Comment by jancborchardt** [comment]
@ganomi hello? Still there? ;) Can you remove your commit with the overlap please as mentioned above?

**Comment by blizzz** [comment]
Does not seem to take effect in current master. I assume that was intended back then for OC 7. The bookmark apps have had a rewrite since then. I try with stable7 branch, but for master and 8.x we need to adjust it. @jancborchardt want to do this?

**Comment by jancborchardt** [comment]
Follow-up at https://github.com/owncloud/bookmarks/pull/170

**Pull request closed without merging**
