### PR TITLE
[BUGGED!] Added CRUD actions for REST API

### PR DESCRIPTION
**Pull request by rakshazi**
Hello!
Please, help me with some... bug(?). In public controller I wrote following code:
```php
<?php
public function update($user = null, $password = null, $id = null, $url, $title, $tags = array(), $description, $is_public = false)
        {
                if(!$this->isUser($user, $password))
                {
                        return $this->newJsonErrorMessage("User could not be identified");
                }

                Bookmarks::editBookmark($user,$this->db, $id, $url, $title, $tags, $description, $is_public);

                return new JSONResponse(array('status' => 'ok', 'message' => 'Bookmark has been updated. I hope.'));

        }
```

And added the following in routes.php:
```php
<?php
array('name' => 'public#update', 'url' => '/public/rest/v1/bookmarks/{id}', 'verb' => 'PUT')
```

But when I try to do request (all data correct), I got following message: 
```json
{
  "message": "Current user is not logged in"
}
```
and HTTP status code 401. Explain please, what I doing wrong?

Thank you!

pS: API will be ready after fix of this problem. For now, it works only with bookmarks. No tags available now.

### CODE REVIEW

**Comment by rakshazi** [comment]
@MorrisJobke hi!
Can you help me with this?

**Comment by MorrisJobke** [comment]
> Can you help me with this?

Currently on vacation.

@blizzz Can you have a look?

**Comment by rakshazi** [comment]
Hi guys!
Any update on this?

**Comment by rakshazi** [comment]
@MorrisJobke @blizzz any update on this?

**Comment by blizzz** [comment]
> "Current user is not logged in"

This is thrown, when the @PublicPage annotation is missing (which is the case in update(), which is also correct but wrong with your other methods) and a user was not logged in. If you're interested in the code behind: https://github.com/owncloud/core/blob/master/lib/private/appframework/middleware/security/securitymiddleware.php#L105

My best guess is that your call was done unauthenticated?

**Comment by rakshazi** [comment]
@blizzz yes, this problem was in annotations, thank you for help!

**Pull request closed without merging**
