### PR TITLE
remove fixed “oc_”-prefix.

### PR DESCRIPTION
**Pull request by tflidd**
Tried to fix the issue I reported some time ago: https://github.com/owncloud/bookmarks/issues/121
Hope it's ok like that.

### CODE REVIEW

**Comment by blizzz** [comment]
@tflidd Thank you! could you also put bookmark_id and tag in the same line into backticks? Then we can merge imo.

**Comment by tflidd** [comment]
@blizz I added the backticks.

**Comment by blizz** [comment]
Please kill this thread immediately.Brett
 


     On Saturday, April 18, 2015 8:48 AM, tflidd <notifications@github.com> wrote:
   

 @blizz I added the backticks.—

**Comment by blizzz** [comment]
Tested, failing tests are unrelated.

**Pull request merged**
