### PR TITLE
Fix version

### PR DESCRIPTION
**Pull request by DavidPrevot**
Follow up from 2928208f499b191a999e9417969b0b31723a13ce.

Might be too late already, but in case it isn’t…

### CODE REVIEW

**Comment by blizzz** [comment]
Thanks, but we should not go down. Unfortunately it needs to be 0.670000 :( Otherwise it won't be offered to get it downloaded. What a mess I did :-/

**Comment by suraia** [comment]
My two cents: I somehow ended up with version 0.666666 in my installation (not sure whether I grabbed a snapshot at some point). Therefore, no upgrades ran because all released versions are < 0.666666. Maybe the version should be bumped to 1.x to make sure upgrades run for new versions?

**Comment by blizzz** [comment]
@surala as a quickfix, change the version in your DB. Use command line occ for this:

``sudo -u www-data ./occ config:app:set bookmarks installed_version --value 0.6.0`` from within your Next(/own)cloud directory.  (web user depends on your distribution)

**Comment by blizzz** [comment]
Closing, because the version is already at 0.6.2.

**Pull request closed without merging**
